name: 'dev'

on:
  push:
    paths:
      - 'dev/*'
      - '!dev/*/*'
  workflow_call:
    inputs:
      service_name:
        description: 'Service name getting deployed'
        required: false
        default: ''
        type: string
      
jobs:
  call-terraform-workflow:
    uses: awishn02/tf-os-sample/.github/workflows/terraform.yml@main
    with:
      role_arn: 'arn:aws:iam::617296401743:role/TerraformGitHubActionsRole'
      environment: 'dev'
      service_name: ${{ inputs.service_name }}
