name: 'dev'

on:
  push:
    branches:
      - main
    paths:
      - 'dev/*'
      - '!dev/*/*'
      
jobs:
  call-terraform-workflow:
    uses: awishn02/tf-os-sample/.github/workflows/terraform.yml@main
    with:
      role_arn: 'arn:aws:iam::617296401743:role/TerraformGitHubActionsRole'
      environment: 'dev'
