name: 'dev'

on:
  push:
    paths:
      - 'dev/*'
      
jobs:
  call-terraform-workflow:
    uses: ./.github/workflows/terraform.yaml@main
    with:
      role_arn: 'arn:aws:iam::617296401743:role/TerraformGitHubActionsRole'
