# This is a workflow created to run based on a commit made by AWS Proton
# It only works if there is only one resource modified as part of the commit.

name: 'proton-run'

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'env_config.json'

jobs:
  get-deployment-data:
    name: Get Deployment Data
    runs-on: ubuntu-latest
    
    # We only want to perform this if the commit creator is AWS Proton as this
    # workflow assumes that the commit will follow exactly the format provided by
    # AWS Proton.
    #if: github.event.pusher.name == 'aws-connector-for-github'
    if: github.event.pusher.name == 'awishn02'
    
    outputs:
      role-arn: ${{ steps.get-data.outputs.role-arn }}
      environment: ${{ steps.get-data.outputs.environment }}
    
    permissions:
      id-token: write
      contents: read
    
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Get changed files
      id: files
      uses: jitterbit/get-changed-files@v1
      
    - name: Find modified resource
      id: find-modified
      run: |
        found=false
        for changed_file in ${{ steps.files.outputs.all }}; do
          if [[ "$changed_file" == *".proton/deployment-metadata.json" ]]; then
            echo "found file"
            if [[ "$found" == true ]]; then
              echo "More than one resource found to have a new deployment, I'm not sure which one to update, exiting."
              exit 0
            fi
            echo "setting found to true"
            found=true
            echo "setting outputs"
            echo "::set-output name=deployment-metadata-path::$changed_file"
          fi
        done
    
    # echo ::set-output name=environment::$("$modified_resource_arn"##*/)
    - name: Get data
      id: get-data
      run: |
        modified_resource_arn=$(jq '.resourceMetadata.arn' ${{ steps.find-modified.outputs.deployment-metadata-path }})
        echo $modified_resource_arn
        if [[ "$modified_resource_arn" == *":environment/"* ]]; then
          environment_name=${modified_resource_arn##*/}
          echo $environment_name
        fi
        echo "::set-output name=environment::$environment_name"
        
        role_arn=$(jq --arg env $environment_name '.[$env]["role"]' env_config.json)
        echo "::set-output name=role-arn::$role_arn"
    
  call-terraform-workflow:
    needs: get-deployment-data
    uses: awishn02/tf-os-sample/.github/workflows/terraform.yml@main
    with:
      role_arn: ${{ needs.get-deployment-data.outputs.role-arn }}
      environment: ${{ needs.get-deployment-data.outputs.environment }}
